import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ProjectData {
  title: string;
  category: string;
  description: string;
  hypothesis: string;
  methodology: string;
  results: string;
  status: string;
  deadline: string;
  created_at: string;
  report?: string;
}

export const generateProjectPDF = (project: ProjectData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(project.title, pageWidth / 2, yPos, { align: "center" });
  yPos += 15;

  // Category and Status
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Category: ${project.category}`, 20, yPos);
  yPos += 7;
  doc.text(`Status: ${project.status}`, 20, yPos);
  yPos += 7;
  doc.text(`Deadline: ${project.deadline}`, 20, yPos);
  yPos += 15;

  // Description
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Description", 20, yPos);
  yPos += 7;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const descLines = doc.splitTextToSize(project.description || "N/A", pageWidth - 40);
  doc.text(descLines, 20, yPos);
  yPos += descLines.length * 5 + 10;

  // Check if new page needed
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  // Hypothesis
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Hypothesis", 20, yPos);
  yPos += 7;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const hypoLines = doc.splitTextToSize(project.hypothesis || "N/A", pageWidth - 40);
  doc.text(hypoLines, 20, yPos);
  yPos += hypoLines.length * 5 + 10;

  // Check if new page needed
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  // Methodology
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Methodology", 20, yPos);
  yPos += 7;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const methLines = doc.splitTextToSize(project.methodology || "N/A", pageWidth - 40);
  doc.text(methLines, 20, yPos);
  yPos += methLines.length * 5 + 10;

  // Check if new page needed
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  // Results
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Results", 20, yPos);
  yPos += 7;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const resLines = doc.splitTextToSize(project.results || "N/A", pageWidth - 40);
  doc.text(resLines, 20, yPos);
  yPos += resLines.length * 5 + 10;

  // AI Generated Report
  if (project.report) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("AI Generated Analysis", 20, yPos);
    yPos += 7;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const reportLines = doc.splitTextToSize(project.report, pageWidth - 40);
    doc.text(reportLines, 20, yPos);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text(
      `Generated by ScienceHub - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // Save
  doc.save(`${project.title.replace(/[^a-z0-9]/gi, "_")}_report.pdf`);
};
